/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RemoteRouteImport } from './routes/remote'
import { Route as GeofenceRouteImport } from './routes/geofence'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIdRouteImport } from './routes/trips.$id'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicShareTokenRouteImport } from './routes/api/public/share.$token'
import { Route as ApiAdminSetupFleetRouteImport } from './routes/api/admin/setup-fleet'

const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteRoute = RemoteRouteImport.update({
  id: '/remote',
  path: '/remote',
  getParentRoute: () => rootRouteImport,
} as any)
const GeofenceRoute = GeofenceRouteImport.update({
  id: '/geofence',
  path: '/geofence',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIdRoute = TripsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TripsRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShareTokenRoute = ApiPublicShareTokenRouteImport.update({
  id: '/api/public/share/$token',
  path: '/api/public/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSetupFleetRoute = ApiAdminSetupFleetRouteImport.update({
  id: '/api/admin/setup-fleet',
  path: '/api/admin/setup-fleet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fleet': typeof FleetRoute
  '/drivers': typeof DriversRoute
  '/reports': typeof ReportsRoute
  '/alerts': typeof AlertsRoute
  '/geofence': typeof GeofenceRoute
  '/remote': typeof RemoteRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/trips': typeof TripsRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/share/$token': typeof ShareTokenRoute
  '/trips/$id': typeof TripsIdRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/share/$token': typeof ApiPublicShareTokenRoute
  '/api/admin/setup-fleet': typeof ApiAdminSetupFleetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fleet': typeof FleetRoute
  '/drivers': typeof DriversRoute
  '/reports': typeof ReportsRoute
  '/alerts': typeof AlertsRoute
  '/geofence': typeof GeofenceRoute
  '/remote': typeof RemoteRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/trips': typeof TripsRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/share/$token': typeof ShareTokenRoute
  '/trips/$id': typeof TripsIdRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/share/$token': typeof ApiPublicShareTokenRoute
  '/api/admin/setup-fleet': typeof ApiAdminSetupFleetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fleet': typeof FleetRoute
  '/drivers': typeof DriversRoute
  '/reports': typeof ReportsRoute
  '/alerts': typeof AlertsRoute
  '/geofence': typeof GeofenceRoute
  '/remote': typeof RemoteRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/trips': typeof TripsRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/share/$token': typeof ShareTokenRoute
  '/trips/$id': typeof TripsIdRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/admin/setup-fleet': typeof ApiAdminSetupFleetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fleet'
    | '/drivers'
    | '/reports'
    | '/alerts'
    | '/geofence'
    | '/remote'
    | '/settings'
    | '/stats'
    | '/trips'
    | '/auth/login'
    | '/share/$token'
    | '/trips/$id'
    | '/api/public/ingest'
    | '/api/public/share/$token'
    | '/api/admin/setup-fleet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fleet'
    | '/drivers'
    | '/reports'
    | '/alerts'
    | '/geofence'
    | '/remote'
    | '/settings'
    | '/stats'
    | '/trips'
    | '/auth/login'
    | '/share/$token'
    | '/trips/$id'
    | '/api/public/ingest'
    | '/api/public/share/$token'
    | '/api/admin/setup-fleet'
  id:
    | '__root__'
    | '/'
    | '/fleet'
    | '/drivers'
    | '/reports'
    | '/alerts'
    | '/geofence'
    | '/remote'
    | '/settings'
    | '/stats'
    | '/trips'
    | '/auth/login'
    | '/share/$token'
    | '/trips/$id'
    | '/api/public/ingest'
    | '/api/public/share/$token'
    | '/api/admin/setup-fleet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FleetRoute: typeof FleetRoute
  DriversRoute: typeof DriversRoute
  ReportsRoute: typeof ReportsRoute
  AlertsRoute: typeof AlertsRoute
  GeofenceRoute: typeof GeofenceRoute
  RemoteRoute: typeof RemoteRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  TripsRoute: typeof TripsRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicShareTokenRoute: typeof ApiPublicShareTokenRoute
  ApiAdminSetupFleetRoute: typeof ApiAdminSetupFleetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote': {
      id: '/remote'
      path: '/remote'
      fullPath: '/remote'
      preLoaderRoute: typeof RemoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofence': {
      id: '/geofence'
      path: '/geofence'
      fullPath: '/geofence'
      preLoaderRoute: typeof GeofenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$id': {
      id: '/trips/$id'
      path: '/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof TripsIdRouteImport
      parentRoute: typeof TripsRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/share/$token': {
      id: '/api/public/share/$token'
      path: '/api/public/share/$token'
      fullPath: '/api/public/share/$token'
      preLoaderRoute: typeof ApiPublicShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/setup-fleet': {
      id: '/api/admin/setup-fleet'
      path: '/api/admin/setup-fleet'
      fullPath: '/api/admin/setup-fleet'
      preLoaderRoute: typeof ApiAdminSetupFleetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TripsRouteChildren {
  TripsIdRoute: typeof TripsIdRoute
}

const TripsRouteChildren: TripsRouteChildren = {
  TripsIdRoute: TripsIdRoute,
}

const TripsRouteWithChildren = TripsRoute._addFileChildren(TripsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FleetRoute: FleetRoute,
  DriversRoute: DriversRoute,
  ReportsRoute: ReportsRoute,
  AlertsRoute: AlertsRoute,
  GeofenceRoute: GeofenceRoute,
  RemoteRoute: RemoteRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  TripsRoute: TripsRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicShareTokenRoute: ApiPublicShareTokenRoute,
  ApiAdminSetupFleetRoute: ApiAdminSetupFleetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
